// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: taskx/proto/taskx.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskXService_DeliverTask_FullMethodName            = "/taskx.TaskXService/DeliverTask"
	TaskXService_DeliverSubtask_FullMethodName         = "/taskx.TaskXService/DeliverSubtask"
	TaskXService_DeliverSubtaskRollback_FullMethodName = "/taskx.TaskXService/DeliverSubtaskRollback"
	TaskXService_HandleTaskImmediately_FullMethodName  = "/taskx.TaskXService/HandleTaskImmediately"
)

// TaskXServiceClient is the client API for TaskXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskXServiceClient interface {
	DeliverTask(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
	DeliverSubtask(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
	DeliverSubtaskRollback(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
	HandleTaskImmediately(ctx context.Context, in *HandleTaskImmediatelyRequest, opts ...grpc.CallOption) (*HandleTaskImmediatelyResponse, error)
}

type taskXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskXServiceClient(cc grpc.ClientConnInterface) TaskXServiceClient {
	return &taskXServiceClient{cc}
}

func (c *taskXServiceClient) DeliverTask(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, TaskXService_DeliverTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskXServiceClient) DeliverSubtask(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, TaskXService_DeliverSubtask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskXServiceClient) DeliverSubtaskRollback(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, TaskXService_DeliverSubtaskRollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskXServiceClient) HandleTaskImmediately(ctx context.Context, in *HandleTaskImmediatelyRequest, opts ...grpc.CallOption) (*HandleTaskImmediatelyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleTaskImmediatelyResponse)
	err := c.cc.Invoke(ctx, TaskXService_HandleTaskImmediately_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskXServiceServer is the server API for TaskXService service.
// All implementations must embed UnimplementedTaskXServiceServer
// for forward compatibility.
type TaskXServiceServer interface {
	DeliverTask(context.Context, *DeliverRequest) (*DeliverResponse, error)
	DeliverSubtask(context.Context, *DeliverRequest) (*DeliverResponse, error)
	DeliverSubtaskRollback(context.Context, *DeliverRequest) (*DeliverResponse, error)
	HandleTaskImmediately(context.Context, *HandleTaskImmediatelyRequest) (*HandleTaskImmediatelyResponse, error)
	mustEmbedUnimplementedTaskXServiceServer()
}

// UnimplementedTaskXServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskXServiceServer struct{}

func (UnimplementedTaskXServiceServer) DeliverTask(context.Context, *DeliverRequest) (*DeliverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverTask not implemented")
}
func (UnimplementedTaskXServiceServer) DeliverSubtask(context.Context, *DeliverRequest) (*DeliverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverSubtask not implemented")
}
func (UnimplementedTaskXServiceServer) DeliverSubtaskRollback(context.Context, *DeliverRequest) (*DeliverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverSubtaskRollback not implemented")
}
func (UnimplementedTaskXServiceServer) HandleTaskImmediately(context.Context, *HandleTaskImmediatelyRequest) (*HandleTaskImmediatelyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleTaskImmediately not implemented")
}
func (UnimplementedTaskXServiceServer) mustEmbedUnimplementedTaskXServiceServer() {}
func (UnimplementedTaskXServiceServer) testEmbeddedByValue()                      {}

// UnsafeTaskXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskXServiceServer will
// result in compilation errors.
type UnsafeTaskXServiceServer interface {
	mustEmbedUnimplementedTaskXServiceServer()
}

func RegisterTaskXServiceServer(s grpc.ServiceRegistrar, srv TaskXServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskXServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskXService_ServiceDesc, srv)
}

func _TaskXService_DeliverTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskXServiceServer).DeliverTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskXService_DeliverTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskXServiceServer).DeliverTask(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskXService_DeliverSubtask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskXServiceServer).DeliverSubtask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskXService_DeliverSubtask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskXServiceServer).DeliverSubtask(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskXService_DeliverSubtaskRollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskXServiceServer).DeliverSubtaskRollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskXService_DeliverSubtaskRollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskXServiceServer).DeliverSubtaskRollback(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskXService_HandleTaskImmediately_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleTaskImmediatelyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskXServiceServer).HandleTaskImmediately(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskXService_HandleTaskImmediately_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskXServiceServer).HandleTaskImmediately(ctx, req.(*HandleTaskImmediatelyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskXService_ServiceDesc is the grpc.ServiceDesc for TaskXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskx.TaskXService",
	HandlerType: (*TaskXServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverTask",
			Handler:    _TaskXService_DeliverTask_Handler,
		},
		{
			MethodName: "DeliverSubtask",
			Handler:    _TaskXService_DeliverSubtask_Handler,
		},
		{
			MethodName: "DeliverSubtaskRollback",
			Handler:    _TaskXService_DeliverSubtaskRollback_Handler,
		},
		{
			MethodName: "HandleTaskImmediately",
			Handler:    _TaskXService_HandleTaskImmediately_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taskx/proto/taskx.proto",
}
