// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: taskx/proto/taskx.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_taskx_proto_taskx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskx_proto_taskx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_taskx_proto_taskx_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeliverRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type DeliverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_taskx_proto_taskx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskx_proto_taskx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_taskx_proto_taskx_proto_rawDescGZIP(), []int{1}
}

type HandleTaskImmediatelyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskIds       []string               `protobuf:"bytes,1,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTaskImmediatelyRequest) Reset() {
	*x = HandleTaskImmediatelyRequest{}
	mi := &file_taskx_proto_taskx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTaskImmediatelyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTaskImmediatelyRequest) ProtoMessage() {}

func (x *HandleTaskImmediatelyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_taskx_proto_taskx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTaskImmediatelyRequest.ProtoReflect.Descriptor instead.
func (*HandleTaskImmediatelyRequest) Descriptor() ([]byte, []int) {
	return file_taskx_proto_taskx_proto_rawDescGZIP(), []int{2}
}

func (x *HandleTaskImmediatelyRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

func (x *HandleTaskImmediatelyRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type HandleTaskImmediatelyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTaskImmediatelyResponse) Reset() {
	*x = HandleTaskImmediatelyResponse{}
	mi := &file_taskx_proto_taskx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTaskImmediatelyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTaskImmediatelyResponse) ProtoMessage() {}

func (x *HandleTaskImmediatelyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_taskx_proto_taskx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTaskImmediatelyResponse.ProtoReflect.Descriptor instead.
func (*HandleTaskImmediatelyResponse) Descriptor() ([]byte, []int) {
	return file_taskx_proto_taskx_proto_rawDescGZIP(), []int{3}
}

var File_taskx_proto_taskx_proto protoreflect.FileDescriptor

const file_taskx_proto_taskx_proto_rawDesc = "" +
	"\n" +
	"\x17taskx/proto/taskx.proto\x12\x05taskx\"=\n" +
	"\x0eDeliverRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\x11\n" +
	"\x0fDeliverResponse\"T\n" +
	"\x1cHandleTaskImmediatelyRequest\x12\x19\n" +
	"\btask_ids\x18\x01 \x03(\tR\ataskIds\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\x1f\n" +
	"\x1dHandleTaskImmediatelyResponse2\xba\x02\n" +
	"\fTaskXService\x12<\n" +
	"\vDeliverTask\x12\x15.taskx.DeliverRequest\x1a\x16.taskx.DeliverResponse\x12?\n" +
	"\x0eDeliverSubtask\x12\x15.taskx.DeliverRequest\x1a\x16.taskx.DeliverResponse\x12G\n" +
	"\x16DeliverSubtaskRollback\x12\x15.taskx.DeliverRequest\x1a\x16.taskx.DeliverResponse\x12b\n" +
	"\x15HandleTaskImmediately\x12#.taskx.HandleTaskImmediatelyRequest\x1a$.taskx.HandleTaskImmediatelyResponseB/Z-github.com/caiflower/common-tools/taskx/protob\x06proto3"

var (
	file_taskx_proto_taskx_proto_rawDescOnce sync.Once
	file_taskx_proto_taskx_proto_rawDescData []byte
)

func file_taskx_proto_taskx_proto_rawDescGZIP() []byte {
	file_taskx_proto_taskx_proto_rawDescOnce.Do(func() {
		file_taskx_proto_taskx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_taskx_proto_taskx_proto_rawDesc), len(file_taskx_proto_taskx_proto_rawDesc)))
	})
	return file_taskx_proto_taskx_proto_rawDescData
}

var file_taskx_proto_taskx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_taskx_proto_taskx_proto_goTypes = []any{
	(*DeliverRequest)(nil),                // 0: taskx.DeliverRequest
	(*DeliverResponse)(nil),               // 1: taskx.DeliverResponse
	(*HandleTaskImmediatelyRequest)(nil),  // 2: taskx.HandleTaskImmediatelyRequest
	(*HandleTaskImmediatelyResponse)(nil), // 3: taskx.HandleTaskImmediatelyResponse
}
var file_taskx_proto_taskx_proto_depIdxs = []int32{
	0, // 0: taskx.TaskXService.DeliverTask:input_type -> taskx.DeliverRequest
	0, // 1: taskx.TaskXService.DeliverSubtask:input_type -> taskx.DeliverRequest
	0, // 2: taskx.TaskXService.DeliverSubtaskRollback:input_type -> taskx.DeliverRequest
	2, // 3: taskx.TaskXService.HandleTaskImmediately:input_type -> taskx.HandleTaskImmediatelyRequest
	1, // 4: taskx.TaskXService.DeliverTask:output_type -> taskx.DeliverResponse
	1, // 5: taskx.TaskXService.DeliverSubtask:output_type -> taskx.DeliverResponse
	1, // 6: taskx.TaskXService.DeliverSubtaskRollback:output_type -> taskx.DeliverResponse
	3, // 7: taskx.TaskXService.HandleTaskImmediately:output_type -> taskx.HandleTaskImmediatelyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_taskx_proto_taskx_proto_init() }
func file_taskx_proto_taskx_proto_init() {
	if File_taskx_proto_taskx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_taskx_proto_taskx_proto_rawDesc), len(file_taskx_proto_taskx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_taskx_proto_taskx_proto_goTypes,
		DependencyIndexes: file_taskx_proto_taskx_proto_depIdxs,
		MessageInfos:      file_taskx_proto_taskx_proto_msgTypes,
	}.Build()
	File_taskx_proto_taskx_proto = out.File
	file_taskx_proto_taskx_proto_goTypes = nil
	file_taskx_proto_taskx_proto_depIdxs = nil
}
