// Code generated by caiflower generator; DO NOT EDIT.
package model

import (
	"fmt"
	"github.com/caiflower/common-tools/pkg/basic"
	"github.com/uptrace/bun"
)

// TaskEdge generate from table task_edge
type TaskEdge struct {
	bun.BaseModel `bun:"table:task_edge"`
	ID            string     `bun:"id,pk,notnull" json:"id"`                      // 边ID
	TaskID        string     `bun:"task_id,notnull" json:"taskID"`                // 所属任务ID
	FromSubtaskID string     `bun:"from_subtask_id,notnull" json:"fromSubtaskID"` // 源子任务ID
	ToSubtaskID   string     `bun:"to_subtask_id,notnull" json:"toSubtaskID"`     // 目标子任务ID
	EdgeType      string     `bun:"edge_type,notnull" json:"edgeType"`            // 边类型(control, data, control+data)
	FieldMappings string     `bun:"field_mappings" json:"fieldMappings"`          // 字段映射JSON
	CreateTime    basic.Time `bun:"create_time" json:"createTime"`                // 创建时间
}

type TaskEdgeFilter struct {
	Page        int      `json:"page"`
	PageSize    int      `json:"pageSize"`
	DisablePage bool     `json:"disablePage"`
	Orders      []string `json:"orders,omitempty"`

	ID            []string     `json:"id,omitempty"`
	TaskID        []string     `json:"taskID,omitempty"`
	FromSubtaskID []string     `json:"fromSubtaskID,omitempty"`
	ToSubtaskID   []string     `json:"toSubtaskID,omitempty"`
	EdgeType      []string     `json:"edgeType,omitempty"`
	FieldMappings []string     `json:"fieldMappings,omitempty"`
	CreateTime    []basic.Time `json:"createTime,omitempty"`
	CreateTimeOp  string       `json:"createTimeOp,omitempty"`
}

func (f *TaskEdgeFilter) GetPage() (offset int, limit int, disable bool) {
	if f.DisablePage {
		return 0, 0, true
	}
	page := f.Page
	if page <= 0 {
		page = 1
	}
	size := f.PageSize
	if size <= 0 {
		size = 10
	}
	return (page - 1) * size, size, false
}

func (f *TaskEdgeFilter) WithID(v ...string) *TaskEdgeFilter {
	f.ID = v
	return f
}

func (f *TaskEdgeFilter) WithTaskID(v ...string) *TaskEdgeFilter {
	f.TaskID = v
	return f
}

func (f *TaskEdgeFilter) WithFromSubtaskID(v ...string) *TaskEdgeFilter {
	f.FromSubtaskID = v
	return f
}

func (f *TaskEdgeFilter) WithToSubtaskID(v ...string) *TaskEdgeFilter {
	f.ToSubtaskID = v
	return f
}

func (f *TaskEdgeFilter) WithEdgeType(v ...string) *TaskEdgeFilter {
	f.EdgeType = v
	return f
}

func (f *TaskEdgeFilter) WithFieldMappings(v ...string) *TaskEdgeFilter {
	f.FieldMappings = v
	return f
}

func (f *TaskEdgeFilter) WithCreateTimeOp(op string, v basic.Time) *TaskEdgeFilter {
	f.CreateTime = []basic.Time{v}
	f.CreateTimeOp = op
	return f
}

func (f *TaskEdgeFilter) WithCreateTime(start, end basic.Time) *TaskEdgeFilter {
	f.CreateTime = []basic.Time{start, end}
	return f
}

func (f *TaskEdgeFilter) WithPage(page int) *TaskEdgeFilter {
	f.Page = page
	return f
}

func (f *TaskEdgeFilter) WithPageSize(pageSize int) *TaskEdgeFilter {
	f.PageSize = pageSize
	return f
}

func (f *TaskEdgeFilter) WithDisablePage(disable bool) *TaskEdgeFilter {
	f.DisablePage = disable
	return f
}

func (f *TaskEdgeFilter) WithOrders(orders ...string) *TaskEdgeFilter {
	f.Orders = orders
	return f
}

func (f *TaskEdgeFilter) Filter(db bun.IDB) *bun.SelectQuery {
	q := db.NewSelect()
	if len(f.ID) > 0 {
		if len(f.ID) == 1 {
			q.Where("id = ?", f.ID[0])
		} else {
			q.Where("id IN (?)", bun.List(f.ID))
		}
	}
	if len(f.TaskID) > 0 {
		if len(f.TaskID) == 1 {
			q.Where("task_id = ?", f.TaskID[0])
		} else {
			q.Where("task_id IN (?)", bun.List(f.TaskID))
		}
	}
	if len(f.FromSubtaskID) > 0 {
		if len(f.FromSubtaskID) == 1 {
			q.Where("from_subtask_id = ?", f.FromSubtaskID[0])
		} else {
			q.Where("from_subtask_id IN (?)", bun.List(f.FromSubtaskID))
		}
	}
	if len(f.ToSubtaskID) > 0 {
		if len(f.ToSubtaskID) == 1 {
			q.Where("to_subtask_id = ?", f.ToSubtaskID[0])
		} else {
			q.Where("to_subtask_id IN (?)", bun.List(f.ToSubtaskID))
		}
	}
	if len(f.EdgeType) > 0 {
		if len(f.EdgeType) == 1 {
			q.Where("edge_type = ?", f.EdgeType[0])
		} else {
			q.Where("edge_type IN (?)", bun.List(f.EdgeType))
		}
	}
	if len(f.FieldMappings) > 0 {
		if len(f.FieldMappings) == 1 {
			q.Where("field_mappings = ?", f.FieldMappings[0])
		} else {
			q.Where("field_mappings IN (?)", bun.List(f.FieldMappings))
		}
	}
	if len(f.CreateTime) > 0 {
		if len(f.CreateTime) == 1 {
			q.Where(fmt.Sprintf("create_time %s ?", f.CreateTimeOp), f.CreateTime[0].Time())
		} else if len(f.CreateTime) == 2 {
			q.Where("create_time BETWEEN ? AND ?", f.CreateTime[0].Time(), f.CreateTime[1].Time())
		}
	}
	if len(f.Orders) > 0 {
		q.Order(f.Orders...)
	} else {
		q.Order("id desc")
	}
	return q
}
