// Code generated by caiflower generator; DO NOT EDIT.
package model

import (
	"fmt"
	"github.com/caiflower/common-tools/pkg/basic"
	"github.com/uptrace/bun"
)

// Task generate from table task
type Task struct {
	bun.BaseModel    `bun:"table:task"`
	ID               string     `bun:"id,pk,notnull" json:"id"`                           // 任务ID
	RequestID        string     `bun:"request_id" json:"requestID"`                       // 请求ID
	TaskName         string     `bun:"task_name" json:"taskName"`                         // 任务名称
	Input            string     `bun:"input" json:"input"`                                // 任务输入参数
	Output           string     `bun:"output" json:"output"`                              // 任务输出结果
	Worker           string     `bun:"worker" json:"worker"`                              // 执行任务的工作节点
	Retry            int8       `bun:"retry" json:"retry"`                                // 剩余重试次数
	RetryInterval    int32      `bun:"retry_interval" json:"retryInterval"`               // 重试间隔(秒)
	Urgent           bool       `bun:"urgent" json:"urgent"`                              // 是否紧急任务(0:否, 1:是)
	State            string     `bun:"state" json:"state"`                                // 任务状态
	Description      string     `bun:"description" json:"description"`                    // 任务描述
	CreateTime       basic.Time `bun:"create_time" json:"createTime"`                     // 创建时间
	LastRunTime      basic.Time `bun:"last_run_time" json:"lastRunTime"`                  // 最后执行时间
	ExecuteTime      basic.Time `bun:"execute_time" json:"executeTime"`                   // 定时执行时间
	Status           int8       `bun:"status" json:"status"`                              // 任务状态(0:禁用, 1:启用)
	AffinityType     string     `bun:"affinity_type" json:"affinityType"`                 // 亲和性类型(SameNode, ForceSameNode, Random)
	PrimaryWorker    string     `bun:"primary_worker" json:"primaryWorker"`               // 主要执行节点
	RollbackStrategy string     `bun:"rollback_strategy,notnull" json:"rollbackStrategy"` // 回滚策略(rollback_all, rollback_failed, rollback_custom)
}

type TaskFilter struct {
	Page        int      `json:"page"`
	PageSize    int      `json:"pageSize"`
	DisablePage bool     `json:"disablePage"`
	Orders      []string `json:"orders,omitempty"`

	ID               []string     `json:"id,omitempty"`
	RequestID        []string     `json:"requestID,omitempty"`
	TaskName         []string     `json:"taskName,omitempty"`
	Input            []string     `json:"input,omitempty"`
	Output           []string     `json:"output,omitempty"`
	Worker           []string     `json:"worker,omitempty"`
	Retry            []int8       `json:"retry,omitempty"`
	RetryInterval    []int32      `json:"retryInterval,omitempty"`
	Urgent           []bool       `json:"urgent,omitempty"`
	State            []string     `json:"state,omitempty"`
	Description      []string     `json:"description,omitempty"`
	CreateTime       []basic.Time `json:"createTime,omitempty"`
	CreateTimeOp     string       `json:"createTimeOp,omitempty"`
	LastRunTime      []basic.Time `json:"lastRunTime,omitempty"`
	LastRunTimeOp    string       `json:"lastRunTimeOp,omitempty"`
	ExecuteTime      []basic.Time `json:"executeTime,omitempty"`
	ExecuteTimeOp    string       `json:"executeTimeOp,omitempty"`
	Status           []int        `json:"status,omitempty"`
	AffinityType     []string     `json:"affinityType,omitempty"`
	PrimaryWorker    []string     `json:"primaryWorker,omitempty"`
	RollbackStrategy []string     `json:"rollbackStrategy,omitempty"`
}

func (f *TaskFilter) GetPage() (offset int, limit int, disable bool) {
	if f.DisablePage {
		return 0, 0, true
	}
	page := f.Page
	if page <= 0 {
		page = 1
	}
	size := f.PageSize
	if size <= 0 {
		size = 10
	}
	return (page - 1) * size, size, false
}

func (f *TaskFilter) WithID(v ...string) *TaskFilter {
	f.ID = v
	return f
}

func (f *TaskFilter) WithRequestID(v ...string) *TaskFilter {
	f.RequestID = v
	return f
}

func (f *TaskFilter) WithTaskName(v ...string) *TaskFilter {
	f.TaskName = v
	return f
}

func (f *TaskFilter) WithInput(v ...string) *TaskFilter {
	f.Input = v
	return f
}

func (f *TaskFilter) WithOutput(v ...string) *TaskFilter {
	f.Output = v
	return f
}

func (f *TaskFilter) WithWorker(v ...string) *TaskFilter {
	f.Worker = v
	return f
}

func (f *TaskFilter) WithRetry(v ...int8) *TaskFilter {
	f.Retry = v
	return f
}

func (f *TaskFilter) WithRetryInterval(v ...int32) *TaskFilter {
	f.RetryInterval = v
	return f
}

func (f *TaskFilter) WithUrgent(v ...bool) *TaskFilter {
	f.Urgent = v
	return f
}

func (f *TaskFilter) WithState(v ...string) *TaskFilter {
	f.State = v
	return f
}

func (f *TaskFilter) WithDescription(v ...string) *TaskFilter {
	f.Description = v
	return f
}

func (f *TaskFilter) WithCreateTimeOp(op string, v basic.Time) *TaskFilter {
	f.CreateTime = []basic.Time{v}
	f.CreateTimeOp = op
	return f
}

func (f *TaskFilter) WithCreateTime(start, end basic.Time) *TaskFilter {
	f.CreateTime = []basic.Time{start, end}
	return f
}

func (f *TaskFilter) WithLastRunTimeOp(op string, v basic.Time) *TaskFilter {
	f.LastRunTime = []basic.Time{v}
	f.LastRunTimeOp = op
	return f
}

func (f *TaskFilter) WithLastRunTime(start, end basic.Time) *TaskFilter {
	f.LastRunTime = []basic.Time{start, end}
	return f
}

func (f *TaskFilter) WithExecuteTimeOp(op string, v basic.Time) *TaskFilter {
	f.ExecuteTime = []basic.Time{v}
	f.ExecuteTimeOp = op
	return f
}

func (f *TaskFilter) WithExecuteTime(start, end basic.Time) *TaskFilter {
	f.ExecuteTime = []basic.Time{start, end}
	return f
}

func (f *TaskFilter) WithStatus(v ...int) *TaskFilter {
	f.Status = v
	return f
}

func (f *TaskFilter) WithAffinityType(v ...string) *TaskFilter {
	f.AffinityType = v
	return f
}

func (f *TaskFilter) WithPrimaryWorker(v ...string) *TaskFilter {
	f.PrimaryWorker = v
	return f
}

func (f *TaskFilter) WithRollbackStrategy(v ...string) *TaskFilter {
	f.RollbackStrategy = v
	return f
}

func (f *TaskFilter) WithPage(page int) *TaskFilter {
	f.Page = page
	return f
}

func (f *TaskFilter) WithPageSize(pageSize int) *TaskFilter {
	f.PageSize = pageSize
	return f
}

func (f *TaskFilter) WithDisablePage(disable bool) *TaskFilter {
	f.DisablePage = disable
	return f
}

func (f *TaskFilter) WithOrders(orders ...string) *TaskFilter {
	f.Orders = orders
	return f
}

func (f *TaskFilter) Filter(db bun.IDB) *bun.SelectQuery {
	q := db.NewSelect()
	if len(f.Status) == 0 {
		q.Where("status>0")
	}
	if len(f.ID) > 0 {
		if len(f.ID) == 1 {
			q.Where("id = ?", f.ID[0])
		} else {
			q.Where("id IN (?)", bun.List(f.ID))
		}
	}
	if len(f.RequestID) > 0 {
		if len(f.RequestID) == 1 {
			q.Where("request_id = ?", f.RequestID[0])
		} else {
			q.Where("request_id IN (?)", bun.List(f.RequestID))
		}
	}
	if len(f.TaskName) > 0 {
		if len(f.TaskName) == 1 {
			q.Where("task_name = ?", f.TaskName[0])
		} else {
			q.Where("task_name IN (?)", bun.List(f.TaskName))
		}
	}
	if len(f.Input) > 0 {
		if len(f.Input) == 1 {
			q.Where("input = ?", f.Input[0])
		} else {
			q.Where("input IN (?)", bun.List(f.Input))
		}
	}
	if len(f.Output) > 0 {
		if len(f.Output) == 1 {
			q.Where("output = ?", f.Output[0])
		} else {
			q.Where("output IN (?)", bun.List(f.Output))
		}
	}
	if len(f.Worker) > 0 {
		if len(f.Worker) == 1 {
			q.Where("worker = ?", f.Worker[0])
		} else {
			q.Where("worker IN (?)", bun.List(f.Worker))
		}
	}
	if len(f.Retry) > 0 {
		if len(f.Retry) == 1 {
			q.Where("retry = ?", f.Retry[0])
		} else {
			q.Where("retry IN (?)", bun.List(f.Retry))
		}
	}
	if len(f.RetryInterval) > 0 {
		if len(f.RetryInterval) == 1 {
			q.Where("retry_interval = ?", f.RetryInterval[0])
		} else {
			q.Where("retry_interval IN (?)", bun.List(f.RetryInterval))
		}
	}
	if len(f.Urgent) > 0 {
		if len(f.Urgent) == 1 {
			q.Where("urgent = ?", f.Urgent[0])
		} else {
			q.Where("urgent IN (?)", bun.List(f.Urgent))
		}
	}
	if len(f.State) > 0 {
		if len(f.State) == 1 {
			q.Where("state = ?", f.State[0])
		} else {
			q.Where("state IN (?)", bun.List(f.State))
		}
	}
	if len(f.Description) > 0 {
		if len(f.Description) == 1 {
			q.Where("description = ?", f.Description[0])
		} else {
			q.Where("description IN (?)", bun.List(f.Description))
		}
	}
	if len(f.CreateTime) > 0 {
		if len(f.CreateTime) == 1 {
			q.Where(fmt.Sprintf("create_time %s ?", f.CreateTimeOp), f.CreateTime[0].Time())
		} else if len(f.CreateTime) == 2 {
			q.Where("create_time BETWEEN ? AND ?", f.CreateTime[0].Time(), f.CreateTime[1].Time())
		}
	}
	if len(f.LastRunTime) > 0 {
		if len(f.LastRunTime) == 1 {
			q.Where(fmt.Sprintf("last_run_time %s ?", f.LastRunTimeOp), f.LastRunTime[0].Time())
		} else if len(f.LastRunTime) == 2 {
			q.Where("last_run_time BETWEEN ? AND ?", f.LastRunTime[0].Time(), f.LastRunTime[1].Time())
		}
	}
	if len(f.ExecuteTime) > 0 {
		if len(f.ExecuteTime) == 1 {
			q.Where(fmt.Sprintf("execute_time %s ?", f.ExecuteTimeOp), f.ExecuteTime[0].Time())
		} else if len(f.ExecuteTime) == 2 {
			q.Where("execute_time BETWEEN ? AND ?", f.ExecuteTime[0].Time(), f.ExecuteTime[1].Time())
		}
	}
	if len(f.Status) > 0 {
		if len(f.Status) == 1 {
			q.Where("status = ?", f.Status[0])
		} else {
			q.Where("status IN (?)", bun.List(f.Status))
		}
	}
	if len(f.AffinityType) > 0 {
		if len(f.AffinityType) == 1 {
			q.Where("affinity_type = ?", f.AffinityType[0])
		} else {
			q.Where("affinity_type IN (?)", bun.List(f.AffinityType))
		}
	}
	if len(f.PrimaryWorker) > 0 {
		if len(f.PrimaryWorker) == 1 {
			q.Where("primary_worker = ?", f.PrimaryWorker[0])
		} else {
			q.Where("primary_worker IN (?)", bun.List(f.PrimaryWorker))
		}
	}
	if len(f.RollbackStrategy) > 0 {
		if len(f.RollbackStrategy) == 1 {
			q.Where("rollback_strategy = ?", f.RollbackStrategy[0])
		} else {
			q.Where("rollback_strategy IN (?)", bun.List(f.RollbackStrategy))
		}
	}
	if len(f.Orders) > 0 {
		q.Order(f.Orders...)
	} else {
		q.Order("id desc")
	}
	return q
}
