// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: dagflow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlowNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                               // task, branch, start, end
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`                       // http, grpc, local, mcp
	ConfigJson    string                 `protobuf:"bytes,5,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // JSON encoded config
	PositionX     float64                `protobuf:"fixed64,6,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY     float64                `protobuf:"fixed64,7,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowNode) Reset() {
	*x = FlowNode{}
	mi := &file_dagflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowNode) ProtoMessage() {}

func (x *FlowNode) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowNode.ProtoReflect.Descriptor instead.
func (*FlowNode) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{0}
}

func (x *FlowNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlowNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlowNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlowNode) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FlowNode) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *FlowNode) GetPositionX() float64 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *FlowNode) GetPositionY() float64 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

type FlowEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // control, data, control+data
	Expr          string                 `protobuf:"bytes,5,opt,name=expr,proto3" json:"expr,omitempty"` // condition expression
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEdge) Reset() {
	*x = FlowEdge{}
	mi := &file_dagflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEdge) ProtoMessage() {}

func (x *FlowEdge) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEdge.ProtoReflect.Descriptor instead.
func (*FlowEdge) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{1}
}

func (x *FlowEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FlowEdge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FlowEdge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *FlowEdge) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlowEdge) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	NodesJson     string                 `protobuf:"bytes,4,opt,name=nodes_json,json=nodesJson,proto3" json:"nodes_json,omitempty"`
	EdgesJson     string                 `protobuf:"bytes,5,opt,name=edges_json,json=edgesJson,proto3" json:"edges_json,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    string                 `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    string                 `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_dagflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{2}
}

func (x *Flow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Flow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flow) GetNodesJson() string {
	if x != nil {
		return x.NodesJson
	}
	return ""
}

func (x *Flow) GetEdgesJson() string {
	if x != nil {
		return x.EdgesJson
	}
	return ""
}

func (x *Flow) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Flow) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Flow) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Flow) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type CreateFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Nodes         []*FlowNode            `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*FlowEdge            `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFlowRequest) Reset() {
	*x = CreateFlowRequest{}
	mi := &file_dagflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFlowRequest) ProtoMessage() {}

func (x *CreateFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFlowRequest.ProtoReflect.Descriptor instead.
func (*CreateFlowRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFlowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFlowRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFlowRequest) GetNodes() []*FlowNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CreateFlowRequest) GetEdges() []*FlowEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GetFlowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: path:"id"
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowRequest) Reset() {
	*x = GetFlowRequest{}
	mi := &file_dagflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowRequest) ProtoMessage() {}

func (x *GetFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowRequest.ProtoReflect.Descriptor instead.
func (*GetFlowRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{4}
}

func (x *GetFlowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFlowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: query:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" query:"page"`
	// @gotags: query:"page_size"
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" query:"page_size"`
	// @gotags: query:"name"
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty" query:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowRequest) Reset() {
	*x = ListFlowRequest{}
	mi := &file_dagflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowRequest) ProtoMessage() {}

func (x *ListFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowRequest.ProtoReflect.Descriptor instead.
func (*ListFlowRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{5}
}

func (x *ListFlowRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFlowRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFlowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Flow                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFlowResponse) Reset() {
	*x = ListFlowResponse{}
	mi := &file_dagflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFlowResponse) ProtoMessage() {}

func (x *ListFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFlowResponse.ProtoReflect.Descriptor instead.
func (*ListFlowResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{6}
}

func (x *ListFlowResponse) GetItems() []*Flow {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFlowResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateFlowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: path:"id"
	Id            string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	Name          string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Nodes         []*FlowNode `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*FlowEdge `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFlowRequest) Reset() {
	*x = UpdateFlowRequest{}
	mi := &file_dagflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFlowRequest) ProtoMessage() {}

func (x *UpdateFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFlowRequest.ProtoReflect.Descriptor instead.
func (*UpdateFlowRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFlowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFlowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFlowRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFlowRequest) GetNodes() []*FlowNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *UpdateFlowRequest) GetEdges() []*FlowEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type DeleteFlowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: path:"id"
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlowRequest) Reset() {
	*x = DeleteFlowRequest{}
	mi := &file_dagflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlowRequest) ProtoMessage() {}

func (x *DeleteFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlowRequest.ProtoReflect.Descriptor instead.
func (*DeleteFlowRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFlowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFlowResponse) Reset() {
	*x = DeleteFlowResponse{}
	mi := &file_dagflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFlowResponse) ProtoMessage() {}

func (x *DeleteFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFlowResponse.ProtoReflect.Descriptor instead.
func (*DeleteFlowResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFlowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flow          *Flow                  `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowResponse) Reset() {
	*x = FlowResponse{}
	mi := &file_dagflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowResponse) ProtoMessage() {}

func (x *FlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowResponse.ProtoReflect.Descriptor instead.
func (*FlowResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{10}
}

func (x *FlowResponse) GetFlow() *Flow {
	if x != nil {
		return x.Flow
	}
	return nil
}

type ValidateFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*FlowNode            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*FlowEdge            `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateFlowRequest) Reset() {
	*x = ValidateFlowRequest{}
	mi := &file_dagflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFlowRequest) ProtoMessage() {}

func (x *ValidateFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFlowRequest.ProtoReflect.Descriptor instead.
func (*ValidateFlowRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateFlowRequest) GetNodes() []*FlowNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ValidateFlowRequest) GetEdges() []*FlowEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type ValidateFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateFlowResponse) Reset() {
	*x = ValidateFlowResponse{}
	mi := &file_dagflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFlowResponse) ProtoMessage() {}

func (x *ValidateFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFlowResponse.ProtoReflect.Descriptor instead.
func (*ValidateFlowResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateFlowResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateFlowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Options       []string               `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_dagflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ConfigField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*ConfigField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_dagflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigSchema) GetFields() []*ConfigField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProtocolInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ConfigSchema  *ConfigSchema          `protobuf:"bytes,4,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolInfo) Reset() {
	*x = ProtocolInfo{}
	mi := &file_dagflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolInfo) ProtoMessage() {}

func (x *ProtocolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolInfo.ProtoReflect.Descriptor instead.
func (*ProtocolInfo) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{15}
}

func (x *ProtocolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtocolInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProtocolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProtocolInfo) GetConfigSchema() *ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

type ListProtocolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProtocolRequest) Reset() {
	*x = ListProtocolRequest{}
	mi := &file_dagflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProtocolRequest) ProtoMessage() {}

func (x *ListProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProtocolRequest.ProtoReflect.Descriptor instead.
func (*ListProtocolRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{16}
}

type ListProtocolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProtocolInfo        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProtocolResponse) Reset() {
	*x = ListProtocolResponse{}
	mi := &file_dagflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProtocolResponse) ProtoMessage() {}

func (x *ListProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProtocolResponse.ProtoReflect.Descriptor instead.
func (*ListProtocolResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{17}
}

func (x *ListProtocolResponse) GetItems() []*ProtocolInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetProtocolRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: path:"name"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" path:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProtocolRequest) Reset() {
	*x = GetProtocolRequest{}
	mi := &file_dagflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProtocolRequest) ProtoMessage() {}

func (x *GetProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProtocolRequest.ProtoReflect.Descriptor instead.
func (*GetProtocolRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{18}
}

func (x *GetProtocolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProtocolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      *ProtocolInfo          `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolResponse) Reset() {
	*x = ProtocolResponse{}
	mi := &file_dagflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolResponse) ProtoMessage() {}

func (x *ProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolResponse.ProtoReflect.Descriptor instead.
func (*ProtocolResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{19}
}

func (x *ProtocolResponse) GetProtocol() *ProtocolInfo {
	if x != nil {
		return x.Protocol
	}
	return nil
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Input         string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`   // JSON encoded input
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"` // JSON encoded output (or error)
	StartTime     string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationMs    int64                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	NodeType      string                 `protobuf:"bytes,9,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // task, branch, start, end
	Protocol      string                 `protobuf:"bytes,10,opt,name=protocol,proto3" json:"protocol,omitempty"`                // http, grpc, local, mcp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_dagflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{20}
}

func (x *NodeStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeStatus) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *NodeStatus) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *NodeStatus) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *NodeStatus) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *NodeStatus) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *NodeStatus) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeStatus) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	FlowName      string                 `protobuf:"bytes,3,opt,name=flow_name,json=flowName,proto3" json:"flow_name,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Nodes         []*NodeStatus          `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	TaskId        string                 `protobuf:"bytes,8,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_dagflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{21}
}

func (x *Execution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Execution) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *Execution) GetFlowName() string {
	if x != nil {
		return x.FlowName
	}
	return ""
}

func (x *Execution) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Execution) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Execution) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Execution) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Execution) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type NodeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"` // JSON encoded input
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInput) Reset() {
	*x = NodeInput{}
	mi := &file_dagflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInput) ProtoMessage() {}

func (x *NodeInput) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInput.ProtoReflect.Descriptor instead.
func (*NodeInput) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{22}
}

func (x *NodeInput) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeInput) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type RunFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	NodeInputs    []*NodeInput           `protobuf:"bytes,2,rep,name=node_inputs,json=nodeInputs,proto3" json:"node_inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunFlowRequest) Reset() {
	*x = RunFlowRequest{}
	mi := &file_dagflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunFlowRequest) ProtoMessage() {}

func (x *RunFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunFlowRequest.ProtoReflect.Descriptor instead.
func (*RunFlowRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{23}
}

func (x *RunFlowRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *RunFlowRequest) GetNodeInputs() []*NodeInput {
	if x != nil {
		return x.NodeInputs
	}
	return nil
}

type GetExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: path:"id"
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" path:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_dagflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{24}
}

func (x *GetExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListExecutionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: query:"page"
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" query:"page"`
	// @gotags: query:"page_size"
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" query:"page_size"`
	// @gotags: query:"flow_id"
	FlowId        string `protobuf:"bytes,3,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty" query:"flow_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionRequest) Reset() {
	*x = ListExecutionRequest{}
	mi := &file_dagflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionRequest) ProtoMessage() {}

func (x *ListExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionRequest) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{25}
}

func (x *ListExecutionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExecutionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExecutionRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type ExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *Execution             `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_dagflow_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{26}
}

func (x *ExecutionResponse) GetExecution() *Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ListExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Execution           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionResponse) Reset() {
	*x = ListExecutionResponse{}
	mi := &file_dagflow_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionResponse) ProtoMessage() {}

func (x *ListExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dagflow_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionResponse) Descriptor() ([]byte, []int) {
	return file_dagflow_proto_rawDescGZIP(), []int{27}
}

func (x *ListExecutionResponse) GetItems() []*Execution {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListExecutionResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_dagflow_proto protoreflect.FileDescriptor

const file_dagflow_proto_rawDesc = "" +
	"\n" +
	"\rdagflow.proto\x12\adagflow\"\xbd\x01\n" +
	"\bFlowNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vconfig_json\x18\x05 \x01(\tR\n" +
	"configJson\x12\x1d\n" +
	"\n" +
	"position_x\x18\x06 \x01(\x01R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\a \x01(\x01R\tpositionY\"r\n" +
	"\bFlowEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04expr\x18\x05 \x01(\tR\x04expr\"\xfe\x01\n" +
	"\x04Flow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"nodes_json\x18\x04 \x01(\tR\tnodesJson\x12\x1d\n" +
	"\n" +
	"edges_json\x18\x05 \x01(\tR\tedgesJson\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\tR\n" +
	"updateTime\"\x9b\x01\n" +
	"\x11CreateFlowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x05nodes\x18\x03 \x03(\v2\x11.dagflow.FlowNodeR\x05nodes\x12'\n" +
	"\x05edges\x18\x04 \x03(\v2\x11.dagflow.FlowEdgeR\x05edges\" \n" +
	"\x0eGetFlowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x0fListFlowRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"M\n" +
	"\x10ListFlowResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.dagflow.FlowR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xab\x01\n" +
	"\x11UpdateFlowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x05nodes\x18\x04 \x03(\v2\x11.dagflow.FlowNodeR\x05nodes\x12'\n" +
	"\x05edges\x18\x05 \x03(\v2\x11.dagflow.FlowEdgeR\x05edges\"#\n" +
	"\x11DeleteFlowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x12DeleteFlowResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"1\n" +
	"\fFlowResponse\x12!\n" +
	"\x04flow\x18\x01 \x01(\v2\r.dagflow.FlowR\x04flow\"g\n" +
	"\x13ValidateFlowRequest\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.dagflow.FlowNodeR\x05nodes\x12'\n" +
	"\x05edges\x18\x02 \x03(\v2\x11.dagflow.FlowEdgeR\x05edges\"B\n" +
	"\x14ValidateFlowResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc8\x01\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x05 \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\aoptions\x18\a \x03(\tR\aoptions\"<\n" +
	"\fConfigSchema\x12,\n" +
	"\x06fields\x18\x01 \x03(\v2\x14.dagflow.ConfigFieldR\x06fields\"\xa3\x01\n" +
	"\fProtocolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12:\n" +
	"\rconfig_schema\x18\x04 \x01(\v2\x15.dagflow.ConfigSchemaR\fconfigSchema\"\x15\n" +
	"\x13ListProtocolRequest\"C\n" +
	"\x14ListProtocolResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.dagflow.ProtocolInfoR\x05items\"(\n" +
	"\x12GetProtocolRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"E\n" +
	"\x10ProtocolResponse\x121\n" +
	"\bprotocol\x18\x01 \x01(\v2\x15.dagflow.ProtocolInfoR\bprotocol\"\x88\x02\n" +
	"\n" +
	"NodeStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\tnode_type\x18\t \x01(\tR\bnodeType\x12\x1a\n" +
	"\bprotocol\x18\n" +
	" \x01(\tR\bprotocol\"\xe5\x01\n" +
	"\tExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\x12\x1b\n" +
	"\tflow_name\x18\x03 \x01(\tR\bflowName\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12)\n" +
	"\x05nodes\x18\a \x03(\v2\x13.dagflow.NodeStatusR\x05nodes\x12\x17\n" +
	"\atask_id\x18\b \x01(\tR\x06taskId\">\n" +
	"\tNodeInput\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\"^\n" +
	"\x0eRunFlowRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x123\n" +
	"\vnode_inputs\x18\x02 \x03(\v2\x12.dagflow.NodeInputR\n" +
	"nodeInputs\"%\n" +
	"\x13GetExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"`\n" +
	"\x14ListExecutionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\aflow_id\x18\x03 \x01(\tR\x06flowId\"E\n" +
	"\x11ExecutionResponse\x120\n" +
	"\texecution\x18\x01 \x01(\v2\x12.dagflow.ExecutionR\texecution\"W\n" +
	"\x15ListExecutionResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.dagflow.ExecutionR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x87\x03\n" +
	"\vFlowService\x12;\n" +
	"\x06Create\x12\x1a.dagflow.CreateFlowRequest\x1a\x15.dagflow.FlowResponse\x125\n" +
	"\x03Get\x12\x17.dagflow.GetFlowRequest\x1a\x15.dagflow.FlowResponse\x12;\n" +
	"\x04List\x12\x18.dagflow.ListFlowRequest\x1a\x19.dagflow.ListFlowResponse\x12;\n" +
	"\x06Update\x12\x1a.dagflow.UpdateFlowRequest\x1a\x15.dagflow.FlowResponse\x12A\n" +
	"\x06Delete\x12\x1a.dagflow.DeleteFlowRequest\x1a\x1b.dagflow.DeleteFlowResponse\x12G\n" +
	"\bValidate\x12\x1c.dagflow.ValidateFlowRequest\x1a\x1d.dagflow.ValidateFlowResponse2\x95\x01\n" +
	"\x0fProtocolService\x12C\n" +
	"\x04List\x12\x1c.dagflow.ListProtocolRequest\x1a\x1d.dagflow.ListProtocolResponse\x12=\n" +
	"\x03Get\x12\x1b.dagflow.GetProtocolRequest\x1a\x19.dagflow.ProtocolResponse2\xd6\x01\n" +
	"\x10ExecutionService\x12:\n" +
	"\x03Run\x12\x17.dagflow.RunFlowRequest\x1a\x1a.dagflow.ExecutionResponse\x12?\n" +
	"\x03Get\x12\x1c.dagflow.GetExecutionRequest\x1a\x1a.dagflow.ExecutionResponse\x12E\n" +
	"\x04List\x12\x1d.dagflow.ListExecutionRequest\x1a\x1e.dagflow.ListExecutionResponseB-Z+github.com/caiflower/dagflow/internal/protob\x06proto3"

var (
	file_dagflow_proto_rawDescOnce sync.Once
	file_dagflow_proto_rawDescData []byte
)

func file_dagflow_proto_rawDescGZIP() []byte {
	file_dagflow_proto_rawDescOnce.Do(func() {
		file_dagflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dagflow_proto_rawDesc), len(file_dagflow_proto_rawDesc)))
	})
	return file_dagflow_proto_rawDescData
}

var file_dagflow_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_dagflow_proto_goTypes = []any{
	(*FlowNode)(nil),              // 0: dagflow.FlowNode
	(*FlowEdge)(nil),              // 1: dagflow.FlowEdge
	(*Flow)(nil),                  // 2: dagflow.Flow
	(*CreateFlowRequest)(nil),     // 3: dagflow.CreateFlowRequest
	(*GetFlowRequest)(nil),        // 4: dagflow.GetFlowRequest
	(*ListFlowRequest)(nil),       // 5: dagflow.ListFlowRequest
	(*ListFlowResponse)(nil),      // 6: dagflow.ListFlowResponse
	(*UpdateFlowRequest)(nil),     // 7: dagflow.UpdateFlowRequest
	(*DeleteFlowRequest)(nil),     // 8: dagflow.DeleteFlowRequest
	(*DeleteFlowResponse)(nil),    // 9: dagflow.DeleteFlowResponse
	(*FlowResponse)(nil),          // 10: dagflow.FlowResponse
	(*ValidateFlowRequest)(nil),   // 11: dagflow.ValidateFlowRequest
	(*ValidateFlowResponse)(nil),  // 12: dagflow.ValidateFlowResponse
	(*ConfigField)(nil),           // 13: dagflow.ConfigField
	(*ConfigSchema)(nil),          // 14: dagflow.ConfigSchema
	(*ProtocolInfo)(nil),          // 15: dagflow.ProtocolInfo
	(*ListProtocolRequest)(nil),   // 16: dagflow.ListProtocolRequest
	(*ListProtocolResponse)(nil),  // 17: dagflow.ListProtocolResponse
	(*GetProtocolRequest)(nil),    // 18: dagflow.GetProtocolRequest
	(*ProtocolResponse)(nil),      // 19: dagflow.ProtocolResponse
	(*NodeStatus)(nil),            // 20: dagflow.NodeStatus
	(*Execution)(nil),             // 21: dagflow.Execution
	(*NodeInput)(nil),             // 22: dagflow.NodeInput
	(*RunFlowRequest)(nil),        // 23: dagflow.RunFlowRequest
	(*GetExecutionRequest)(nil),   // 24: dagflow.GetExecutionRequest
	(*ListExecutionRequest)(nil),  // 25: dagflow.ListExecutionRequest
	(*ExecutionResponse)(nil),     // 26: dagflow.ExecutionResponse
	(*ListExecutionResponse)(nil), // 27: dagflow.ListExecutionResponse
}
var file_dagflow_proto_depIdxs = []int32{
	0,  // 0: dagflow.CreateFlowRequest.nodes:type_name -> dagflow.FlowNode
	1,  // 1: dagflow.CreateFlowRequest.edges:type_name -> dagflow.FlowEdge
	2,  // 2: dagflow.ListFlowResponse.items:type_name -> dagflow.Flow
	0,  // 3: dagflow.UpdateFlowRequest.nodes:type_name -> dagflow.FlowNode
	1,  // 4: dagflow.UpdateFlowRequest.edges:type_name -> dagflow.FlowEdge
	2,  // 5: dagflow.FlowResponse.flow:type_name -> dagflow.Flow
	0,  // 6: dagflow.ValidateFlowRequest.nodes:type_name -> dagflow.FlowNode
	1,  // 7: dagflow.ValidateFlowRequest.edges:type_name -> dagflow.FlowEdge
	13, // 8: dagflow.ConfigSchema.fields:type_name -> dagflow.ConfigField
	14, // 9: dagflow.ProtocolInfo.config_schema:type_name -> dagflow.ConfigSchema
	15, // 10: dagflow.ListProtocolResponse.items:type_name -> dagflow.ProtocolInfo
	15, // 11: dagflow.ProtocolResponse.protocol:type_name -> dagflow.ProtocolInfo
	20, // 12: dagflow.Execution.nodes:type_name -> dagflow.NodeStatus
	22, // 13: dagflow.RunFlowRequest.node_inputs:type_name -> dagflow.NodeInput
	21, // 14: dagflow.ExecutionResponse.execution:type_name -> dagflow.Execution
	21, // 15: dagflow.ListExecutionResponse.items:type_name -> dagflow.Execution
	3,  // 16: dagflow.FlowService.Create:input_type -> dagflow.CreateFlowRequest
	4,  // 17: dagflow.FlowService.Get:input_type -> dagflow.GetFlowRequest
	5,  // 18: dagflow.FlowService.List:input_type -> dagflow.ListFlowRequest
	7,  // 19: dagflow.FlowService.Update:input_type -> dagflow.UpdateFlowRequest
	8,  // 20: dagflow.FlowService.Delete:input_type -> dagflow.DeleteFlowRequest
	11, // 21: dagflow.FlowService.Validate:input_type -> dagflow.ValidateFlowRequest
	16, // 22: dagflow.ProtocolService.List:input_type -> dagflow.ListProtocolRequest
	18, // 23: dagflow.ProtocolService.Get:input_type -> dagflow.GetProtocolRequest
	23, // 24: dagflow.ExecutionService.Run:input_type -> dagflow.RunFlowRequest
	24, // 25: dagflow.ExecutionService.Get:input_type -> dagflow.GetExecutionRequest
	25, // 26: dagflow.ExecutionService.List:input_type -> dagflow.ListExecutionRequest
	10, // 27: dagflow.FlowService.Create:output_type -> dagflow.FlowResponse
	10, // 28: dagflow.FlowService.Get:output_type -> dagflow.FlowResponse
	6,  // 29: dagflow.FlowService.List:output_type -> dagflow.ListFlowResponse
	10, // 30: dagflow.FlowService.Update:output_type -> dagflow.FlowResponse
	9,  // 31: dagflow.FlowService.Delete:output_type -> dagflow.DeleteFlowResponse
	12, // 32: dagflow.FlowService.Validate:output_type -> dagflow.ValidateFlowResponse
	17, // 33: dagflow.ProtocolService.List:output_type -> dagflow.ListProtocolResponse
	19, // 34: dagflow.ProtocolService.Get:output_type -> dagflow.ProtocolResponse
	26, // 35: dagflow.ExecutionService.Run:output_type -> dagflow.ExecutionResponse
	26, // 36: dagflow.ExecutionService.Get:output_type -> dagflow.ExecutionResponse
	27, // 37: dagflow.ExecutionService.List:output_type -> dagflow.ListExecutionResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_dagflow_proto_init() }
func file_dagflow_proto_init() {
	if File_dagflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dagflow_proto_rawDesc), len(file_dagflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_dagflow_proto_goTypes,
		DependencyIndexes: file_dagflow_proto_depIdxs,
		MessageInfos:      file_dagflow_proto_msgTypes,
	}.Build()
	File_dagflow_proto = out.File
	file_dagflow_proto_goTypes = nil
	file_dagflow_proto_depIdxs = nil
}
